# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QSAdManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end
      end
    end
  
  pod 'Google-Mobile-Ads-SDK', '13.1.0'
  pod 'SkeletonView', '1.30.4'
  pod 'SnapKit', '5.7.1'

end
